# tasks to complete before running roles
- hosts: localhost
  tags: always
  connection: local
  become: true
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

# run roles
- hosts: localhost
  vars_prompt:
    - name: USER
      prompt: What is your username?
      private: false
    - name: PWD
      prompt: What is your password?
      
  tags: base
  become: true
  roles:
    - base
