- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - colordiff
      - curl
      - "{{ DNS_UTILS_PACKAGE }}"
      - htop
      - iotop
      - net-tools
      - "{{ NFS_CLIENT_PACKAGE }}"
      - nmap
      - rsync
      - tmux
      - traceroute
      - "{{ VIM_PACKAGE }}"
      - wget
      - whois
      - zsh
      - code
      - tig
      - fzf
      - autojump
      - apt-transport-https 
      - wget
      - software-properties-common
#      - lazygit

- name: system setup | utilities | install man-pages (arch)
  tags: packages,system,settings
  pacman:
    state: latest
    name:
      - man-db
      - man-pages
  when: ansible_distribution == "Archlinux"
