- name: system setup | desktop packages | install packages
  tags: dev,development,packages,python,ruby
  package:
    name:
      - ubuntu-desktop-minimal
      - i3
    state: latest

- name: system setup | desktop packages | install packages 2
  tags: dev,development,packages,python,ruby
  package:
    name:
      - linux-generic-hwe-22.04
    state: latest
  when: 
    - ansible_distribution in ["Ubuntu"]
    - ansible_facts['distribution_major_version'] == "22"
    - ansible_facts['distribution_major_version'] == "04"


- name: system setup | desktop packages | GDM enabling automatic login
  #  AutomaticLoginEnable = true
  #  AutomaticLogin = user1
  become: yes
  block:
  - community.general.ini_file:
      path: /etc/gdm3/custom.conf
      section: daemon
      option: AutomaticLoginEnable
      value: true
  - community.general.ini_file:
      path: /etc/gdm3/custom.conf
      section: daemon
      option: AutomaticLogin
      value: "{{ USER }}"
