- name: system setup | development packages | install packages
  package:
    name:
      - flake8
      - git
      - tree
      - firefox
      - "{{ PYTHON_FLAKE8_PACKAGE }}"
      - "{{ PYTHON_PACKAGE }}"
      - "{{ PYTHON_PIP_PACKAGE }}"
      - "{{ PYTHON_PYFLAKES_PACKAGE }}"
      - python-setuptools
      - "{{ PYTHON_VIRTUALENV_PACKAGE }}"
    state: latest
  become: true  


- name: Add lazy Git (v 0.37)
  shell:  curl -Lo /tmp/lazygit.tar.gz https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_0.37_Linux_x86_64.tar.gz

- name: Extract lazy Git
  archive:
    path:  /tmp/lazygit.tar.gz
    dest:  /usr/local/bin/lazygit
    format: zip
  become: true 


