- name: software | kubectl | install
  shell: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  args:
    warn: no
    
- name: Move kubectl to /usr/local/bin
  command: mv ./kubectl /usr/local/bin

- name: Change file ownership, group and permissions
  file:
    path: /usr/local/bin/kubectl
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: '0777'

- name: software | helm | install
  shell: curl "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3" | bash
  args:
    warn: no

- name: Add Kustomize
  shell: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
  args:
    warn: no

- name: Move kustomize to /usr/local/bin
  command: mv ./kustomize /usr/local/bin

- name: Change file ownership, group and permissions
  file:
    path: /usr/local/bin/kubectl
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: '0777'

- name: software | flux | install
  shell: curl -s "https://fluxcd.io/install.sh" | bash
  args:
    warn: no

#todo
# tektom
# ArgoCLI 
